
exports.config = {
    title: 'Hackathon közönségszavazás',
    titleAdmin: 'Hackathon közönségszavazás * Admin',
    ratings: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    teams: ['ateam', 'eduteam', 'fruitloops', 'fux', 'ignore', 'macgyver', 'pumasimi', 'redduck', 'screamo', 'cod', 'nyitmak'],
    teamNames: {
        'ateam':        {name: 'A Team', boss: 'Gyula', appName: 'Better Presentation with Ustream'},
        'eduteam':      {name: 'Eduteam', boss: 'Csaba', appName: 'Edustream'},
        'fruitloops':   {name: 'Fruit Loops', boss: 'Ajnász', appName: 'Ustream XBMC Plugin'},
        'fux':          {name: 'Fux', boss: 'Kasza Levi', appName: 'Fsx'},
        'ignore':       {name: 'Ignore White Elephant', boss: 'Lombai Feri', appName: 'Solution Finder'},
        'macgyver':     {name: 'Mac Gyver', boss: 'Nádasdi Máté éd.', appName: 'Attention Map'},
        'pumasimi':     {name: 'Puma Simogató Trollok', boss: 'Szabó Feri', appName: 'StreamSquare'},
        'redduck':      {name: 'Red Duck', boss: 'Radnóczi Gergő', appName: 'Whereabouts'},
        'screamo':      {name: 'Screamo', boss: 'Schmidt Gergely', appName: 'FoodStream 2.'},
        'cod':          {name: 'Call of Duty', boss: 'Csergő Bálint', appName: 'OpenDuty'},
        'nyitmak':      {name: 'nyitmákhívó', boss: 'Bieber Norbi', appName: 'Live Alert'}
    },
    users: [
        {code: 'lofasz', email: 'david@ustream.tv', team: 'admin', admin: true},
        {code: 'keresk', email: '', team: 'admin', admin: true},
        {code: 'kolinz', email: '', team: 'admin', admin: true},
        {code: 'kollin', email: '', team: 'admin', admin: true},
        {code: 'tzetze', email: '', team: 'admin', admin: true},
        {code: 'sdavid', email: '', team: 'admin', admin: true},
        {code: 'juhasz', email: '', team: 'admin', admin: true},

        {code: 'OEVnLO', email: 'koszti.lajos@ustream.tv', team: 'fruitloops'},
        {code: 'BhZVn9', email: 'vachter.attila@ustream.tv', team: 'fruitloops'},
        {code: '1I2E7k', email: 'sulik.szabolcs@ustream.tv', team: 'fruitloops'},
        {code: 'Hf2v43', email: 'feher.gyula@ustream.tv', team: 'ateam'},
        {code: 'gooDSs', email: 'alden.fertig@ustream.tv', team: 'ateam'},
        {code: 'whsd3O', email: 'toth.szabolcs@ustream.tv', team: 'ateam'},
        {code: 'uk23NO', email: 'biro.nandor@ustream.tv', team: 'ateam'},
        {code: 'LOLwow', email: 'juhasz.peter@ustream.tv', team: 'ateam'},
        {code: 'doomYO', email: 'kapusi.jozsef@ustream.tv', team: 'ateam'},
        {code: 'yoloB4', email: 'nyitrai.robert@ustream.tv', team: 'ateam'},
        {code: 'fixMEO', email: 'gemesi.mark@ustream.tv', team: 'ateam'},
        {code: 'trL212', email: 'csaba.sipocz@ustream.tv', team: 'eduteam'},
        {code: 'HYH615', email: 'gazdik.richard@ustream.tv', team: 'eduteam'},
        {code: 'nir3r2', email: 'andy.francis@ustream.tv', team: 'eduteam'},
        {code: 'z34sVl', email: 'kasza.levente@ustream.tv', team: 'fux'},
        {code: 'boa2M1', email: 'kolumban.tibor@ustream.tv', team: 'fux'},
        {code: 'iddqdq', email: 'demeny.tamas@ustream.tv', team: 'fux'},
        {code: 'doAvc3', email: 'keres.peter@ustream.tv', team: 'fux'},
        {code: 'POIqw5', email: 'kostyo.nandor@ustream.tv', team: 'fux'},
        {code: 'j2apPS', email: 'vasarhelyi.peter@ustream.tv', team: 'fux'},
        {code: 'LaK3IS', email: 'lombai.ferenc@ustream.tv', team: 'ignore'},
        {code: 'oI2tsr', email: 'janvari.attila@ustream.tv', team: 'ignore'},
        {code: 's6c444', email: 'meszaros.melinda@ustream.tv', team: 'ignore'},
        {code: 'io6758', email: 'blasko.mihaly@ustream.tv', team: 'ignore'},
        {code: 'uiuiui', email: 'nadasdi.mate@ustream.tv', team: 'mcgyver'},
        {code: 'zop411', email: 'karolyi.balazs@ustream.tv', team: 'mcgyver'},
        {code: 'nOa4TT', email: 'szatmari.andras@ustream.tv', team: 'mcgyver'},
        {code: 'p3ok22', email: 'virag@ustream.tv', team: 'mcgyver'},
        {code: 'lk44as', email: 'francsics.balazs@ustream.tv', team: 'mcgyver'},
        {code: 'fik4Sy', email: 'bajkai.gyula@ustream.tv', team: 'mcgyver'},
        {code: 'dgR3HZ', email: 'szabo.ferenc@ustream.tv', team: 'pumasimi'},
        {code: 'i7564w', email: 'mihaly.imre@ustream.tv', team: 'pumasimi'},
        {code: 'fZZyp8', email: 'albertini.bence@ustream.tv', team: 'pumasimi'},
        {code: 'asdftA', email: 'tolmacs.mark@ustream.tv', team: 'pumasimi'},
        {code: 'sdk231', email: 'sallai.gergely@ustream.tv', team: 'pumasimi'},
        {code: 'OOOOaq', email: 'solymosi.tamas@ustream.tv', team: 'pumasimi'},
        {code: 'hgf2as', email: 'felho@ustream.tv', team: 'redduck'},
        {code: 'cxpew3', email: 'gal.jozsef@ustream.tv', team: 'redduck'},
        {code: 'loKIsy', email: 'gonda.attila@ustream.tv', team: 'redduck'},
        {code: 'sc211t', email: 'sipos.csaba@ustream.tv', team: 'redduck'},
        {code: 'PJ1Uw2', email: 'szopory.zoltan@ustream.tv', team: 'redduck'},
        {code: 'Nsa221', email: 'szilagyi.peter@ustream.tv', team: 'redduck'},
        {code: 'poS3iu', email: 'radnoczi.gergely@ustream.tv', team: 'redduck'},
        {code: 'O2H111', email: 'schmidt.gergely@ustream.tv', team: 'screamo'},
        {code: 'Bxp27s', email: 'tillmann.robert@ustream.tv', team: 'screamo'},
        {code: 'PA3Xss', email: 'viktor.honti@ustream.tv', team: 'screamo'},
        {code: 'E26sxg', email: 'foky.balazs@ustream.tv', team: 'screamo'},
        {code: 'L321xi', email: 'csergo.balint@ustream.tv', team: 'cod'},
        {code: 'hC321a', email: 'szalay.atila@ustream.tv', team: 'cod'},
        {code: 'GWase4', email: 'kovacs.ferenc@ustream.tv', team: 'cod'},
        {code: 'XxnoQH', email: 'ecsedi.tamas@ustream.tv', team: 'cod'},
        {code: 'e8qz6k', email: 'takacs.zsolt@ustream.tv', team: 'cod'},
        {code: 'my06rA', email: 'gyimesi.akos@ustream.tv', team: 'cod'},
        {code: 'JN4LYd', email: 'nemeth.zoltan@ustream.tv', team: 'cod'},
        {code: 'YkWeG9', email: 'bieber.norbert@ustream.tv', team: 'nyitmak'},
        {code: 'uQHnDQ', email: 'tothmihaly.gergo@ustream.tv', team: 'nyitmak'},
        {code: 'j3YiT4', email: 'rechner.istvan@ustream.tv', team: 'nyitmak'},
        {code: 'hjdDDV', email: 'balint.istvan@ustream.tv', team: 'nyitmak'},
        {code: 'DVXK4x', email: 'ferenczi.monika@ustream.tv', team: 'nyitmak'},
        {code: 'ZID52T', email: 'szabo.andras@ustream.tv', team: 'nyitmak'}
    ]
};
